repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: prometheus-operator
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    values:
        - namespaceOverride: "monitoring"
          grafana:
            ingress:
              enabled: true
              hosts:  
                - "grafana.joaovitor.local"
            persistence:
              enabled: true
              storageClassName: "longhorn"
              size: 20Gi