apiVersion: v1
kind: Service
metadata:
  name: dashy
  labels:
    app: dashy
    scope: management
  namespace: management
spec:
  selector:
    app: dashy
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
