- name: Restart headscale service
  become: true
  become_user: root
  become_method: sudo
  service:
    name: headscale
    state: restarted
    enabled: true
    daemon-reload: true
  listen: 'restart headscale'
