- name: Add control plane nodes locally
  hosts: oracle_headscale
  become: yes
  become_method: sudo
  vars:
    headscale_version: '0.22.3'
    architecture: arm64
    headscale_config:
      server_url: "https://headscale.{{ connection.domain }}:8080"
      listen_addr: "0.0.0.0:8080"
      metrics_listen_addr: 127.0.0.1:9090
      grpc_listen_addr: 127.0.0.1:50443
      grpc_allow_insecure: false
      private_key_path: /var/lib/headscale/private.key

      noise:
        private_key_path: /var/lib/headscale/noise_private.key

      ip_prefixes:
        - fd7a:115c:a1e0::/48
        - 100.64.0.0/10

      derp:
        server:
          enabled: false
          region_id: 999
          region_code: "headscale"
          region_name: "Headscale Embedded DERP"
          stun_listen_addr: "0.0.0.0:3478"

        urls:
          - https://controlplane.tailscale.com/derpmap/default

        paths: []
        auto_update_enabled: true
        update_frequency: 24h

      disable_check_updates: false
      ephemeral_node_inactivity_timeout: 30m
      node_update_check_interval: 10s

      db_type: postgres
      db_path: /var/lib/headscale/db.sqlite
      db_host: "{{ connection.database.host }}"
      db_port: "{{ connection.database.port }}"
      db_user: "{{ connection.database.user }}"
      db_pass: "{{ connection.database.password }}"
      db_name: headscale
      db_ssl: prefer

      acme_url: https://acme-v02.api.letsencrypt.org/directory
      acme_email: ""
      tls_letsencrypt_hostname: "headscale.{{ connection.domain }}"
      tls_letsencrypt_cache_dir: /var/lib/headscale/cache
      tls_letsencrypt_challenge_type: HTTP-01
      tls_letsencrypt_listen: ":http"
      tls_cert_path: ""
      tls_key_path: ""

      log:
        format: text
        level: debug

      acl_policy_path: ""

      dns_config:
        override_local_dns: true
        nameservers:
          - 100.64.0.1
          - 100.64.0.2
        domains: []
        magic_dns: true
        base_domain: "headscale.{{ connection.domain }}"

      unix_socket: /var/run/headscale/headscale.sock
      unix_socket_permission: "0770"

      logtail:
        enabled: false

      randomize_client_port: false
  roles:
    - headscale