repositories:
  - name: traefik
    url: https://traefik.github.io/charts

releases:
  - name: traefik
    chart: traefik/traefik
    namespace: network
    values:
      - deployment:
          enabled: true
          kind: DaemonSet
          minReadySeconds: 5

        globalArguments:
          - "--global.checknewversion=false"
          - "--global.sendanonymoususage=false"

        additionalArguments:
          - "--serversTransport.insecureSkipVerify=true"
          - "--log.level=DEBUG"